server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: ["*"]
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: rameo
  security:
    user: # 配置安全用户
      name: admin
      password: 123456
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080   #sentinel控制台的请求地址
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos控制台的请求地址
      config:
        server-addr: 127.0.0.1:8848 #nacos控制台的请求地址